[project]
name = "alicebot-plugin-mirai-repeater"
version = "0.0.1"
description = "using mirai adapter, will repeat group member's message randomly"
authors = [{ name = "DekuWang", email = "2873450572@qq.com" }]
license = { text = "MIT" }
readme = "README.md"
keywords = ["bot", "chatbot", "alicebot", "mirai"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: AsyncIO",
    "Framework :: Robot Framework",
    "Framework :: Robot Framework :: Library",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Communications :: Chat",
]
requires-python = ">=3.8"
dependencies = [
    "alicebot>=0.10.0",
    "alicebot-adapter-mirai>=0.10.0",
]

[tool.pdm.dev-dependencies]
lint = ["ruff"]

[project.urls]
Homepage = "https://docs.alicebot.dev/"                                    # TODO
Documentation = "https://docs.alicebot.dev/"                               # TODO
Repository = "https://github.com/AliceBotProject/alicebot-plugin-template" # TODO
Changelog = "https://docs.alicebot.dev/changelog.html"                     # TODO

[tool.ruff]
line-length = 88
target-version = "py38"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D",      # pydocstyle
    "BLE",    # flake8-blind-except
    "FBT",    # flake8-boolean-trap
    "COM",    # flake8-commas
    "EM",     # flake8-errmsg
    "ISC",    # flake8-implicit-str-concat
    "INP",    # flake8-no-pep420
    "TID",    # flake8-tidy-imports
    "E501",   # Line too long, handled by formatter
    "ANN101", # Missing type annotation for self
    "ANN102", # Missing type annotation for cls
    "RUF001", # String contains ambiguous unicode character string
    "RUF002", # Docstring contains ambiguous unicode character string
    "RUF003", # Comment contains ambiguous unicode character string
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pyupgrade]
keep-runtime-typing = true

[tool.pyright]
pythonVersion = "3.8"
pythonPlatform = "All"
typeCheckingMode = "strict"
reportUnnecessaryIsInstance = false

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
